# (C) Copyright 2020 Hewlett Packard Enterprise Development LP
- name: web | copy the eShopcontainer repo to web server
  copy:
    src: ../../eShopOnContainers
    dest: /tmp/
    force: yes

- name: web | copy the env file
  template:
    src: roles/upgrade/templates/env.j2
    dest: /tmp/eShopOnContainers/src/.env
    
- name: web | Install Web component
  command: chdir=/tmp/eShopOnContainers/src/ docker-compose -f docker-compose-web.yml -f docker-compose-web.override.yml build

- name: web | Bring up Web server
  command: chdir=/tmp/eShopOnContainers/src/ docker-compose -f docker-compose-web.yml -f docker-compose-web.override.yml up -d 
